#!/usr/bin/env bash

COMPONENT=$1
VERSION=$2
WRITE_TAG=$3
LAST_TAG=$(git describe --abbrev=0)
RELEASE_NOTES=$(xfce-get-release-notes "$LAST_TAG" silent)
TRANSLATIONS=$(xfce-get-translations "$LAST_TAG" "HEAD" silent)

# Check if there is a NEWS file
if [ "$WRITE_TAG" = "WRITETAG" ]; then
    printf '%s\n\n%s\n%s\n' $VERSION "$RELEASE_NOTES" "$TRANSLATIONS"
elif [ ! -f "NEWS" ]; then
    echo "There is no 'NEWS' file. Changelog since $VERSION:"
    printf '%s\n======\n%s\n%s\n\n%s' $VERSION "$RELEASE_NOTES" "$TRANSLATIONS"
else
    printf '%s\n======\n%s\n%s\n\n%s\n' $VERSION "$RELEASE_NOTES" "$TRANSLATIONS" "$(cat NEWS)" > NEWS
    git diff NEWS
fi
