image: xfce/xfce-build:latest
    
stages:
  - build

build-distcheck:
  stage: build
  script:
    - ./autogen.sh
    - make distcheck
  rules:
    - changes: 
      - "po/*.po"
      when: never

translations:
  stage: build
  script:
    #  Could validate translations, but for now just pass
    - "true"
  rules:
    - changes: 
      - "po/*.po"
      when: always
