image: xfce/xfce-build:latest
    
stages:
  - build
  - distcheck

translations:
  extends: .translation
  stage: build
  script:
    #  Could validate translations, but for now just pass
    - "true"

build:
  extends: .make
  stage: build
  script:
    - make

distcheck:
  extends: .make
  stage: distcheck
  script:
    - make distcheck

.make:
  before_script:
    - ./autogen.sh
  rules:
    # If there are changes to .po, never run. We also check
    # BEFORE_SHA to see if it is zeros, in which case we are
    # running on a manual trigger or scheduled pipeline. In 
    # that case, changes resolves to true so we need to check
    # both.
    - if: '$CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000"'
      changes: 
      - "po/*.po"
      when: never
    # Otherwise, always run
    - when: always

.translation:
  rules:
    # If there are changes to .po, run this job
    - changes: 
      - "po/*.po"
      when: always
    # Otherwise, never run
    - when: never
